services:
  pg:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cPiytKVt4h8R7YqhSASCLm0D8oP9hJjeQtHU5cxFd0M
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "9004:9004"
    restart: always
    networks:
      - app_network

  streamlit:
    environment:
      - BASE_URL=http://fastapi:9002/api
    build:
      context: .
      dockerfile: ./streamlit/Dockerfile
    expose:
      - "9003"
    depends_on:
      - fastapi
    networks:
      - app_network

  fastapi:
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:cPiytKVt4h8R7YqhSASCLm0D8oP9hJjeQtHU5cxFd0M@pg:5432/postgres
      - SECRET_KEY=ygzMCllL4OVfQdvrBflm6UnOgLwWNXvOxcbGHH1tMsM
    build:
      context: .
      dockerfile: ./fastapi/Dockerfile
    expose:
      - "9002"
    depends_on:
      - pg
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9001:9001"
    depends_on:
      - fastapi
      - streamlit
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
