services:
  pg:
    image: postgres:16
    environment:
      - POSTGRES_USER=uhkvulJ-N6kOF0kv_wb1TA9jgpBloYRSWzAuo8zJhao
      - POSTGRES_PASSWORD=cPiytKVt4h8R7YqhSASCLm0D8oP9hJjeQtHU5cxFd0M
      - POSTGRES_DB=postgres
    volumes:
      - ./base:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always