FROM python:3.11-slim

WORKDIR /app

COPY ./streamlit /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 9003

CMD ["streamlit", "run", "streamlit.py", "--server.port=9003", "--server.address=0.0.0.0"]
