FROM python:3.11-slim

WORKDIR /app

COPY ./fastapi /app

RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 9002
RUN mkdir -p /certs

COPY ./fastapi/certs/privkey.pem /app/fastapi/certs/privkey.pem
COPY ./fastapi/certs/fullchain.pem /app/fastapi/certs/fullchain.pem


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9002", "--ssl-keyfile", "/app/fastapi/certs/privkey.pem", "--ssl-certfile", "/app/fastapi/certs/fullchain.pem"]