FROM python:3.11-slim

WORKDIR /app

COPY ./fastapi /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 9002

RUN mkdir -p /certs

COPY privkey.pem fullchain.pem /certs

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9002", "--ssl-keyfile", "./certs/privkey.pem", "--ssl-certfile", "./certs/fullchain.pem"]
